### ISSUE TITLE
[ENH]: Optional quotes

### ISSUE THREAD

**Issue by UTFeight** [2KAbhishek/nerdy.nvim#1]
### Description

When a glyph is inserted in the buffer, It's wrapped around single quotes which bugs me a lot.

Is there a way you can modify the setup function?

```lua
require("nerdy").setup {
    -- surround = "\"" -- custom quotes!
    surround = nil -- or false
}
```

**Comment by 2KAbhishek** [comment]
sure, i'll add an option for this and make unquoted the default option :)
