### ISSUE TITLE
[BUG]: Unsupported layout_config key for the center strategy: preview_width  

### ISSUE THREAD

**Issue by kdurant** [2KAbhishek/nerdy.nvim#2]
### Description of the bug

When I enter ":Nerdy", it will prompt
```
Unsupported layout_config key for the center strategy: preview_width                      
{
  bottom_pane = {
    height = <function 1>,
    preview_cutoff = 1,
    prompt_position = "top"
  },
  center = {
    height = <function 1>,
    preview_cutoff = 1,
    prompt_position = "top",
    width = <function 2>
  },
  cursor = {
    height = <function 1>,
    preview_cutoff = 1,
    width = <function 2>
  },
  height = <function 1>,
  horizontal = {
    height = <function 1>,
    preview_cutoff = 1,
    prompt_position = "bottom",
    width = <function 2>
  },
  preview_cutoff = 1,
  preview_width = 0.5,
  vertical = {
    height = <function 1>,
    preview_cutoff = 1,
    prompt_position = "bottom",
    width = <function 2>
  },
  width = <function 2>
}
```

### Steps To Reproduce

:Nerdy

**Comment by 2KAbhishek** [comment]
Have you installed the dressing.nvim and telescope.nvim plugins?

If so you may want to look at those configs, this does not look like something related to Nerdy

Also try running:
```
:lua vim.ui.select({1,2},{prompt = "hi"},function(item) print(item)  end)   
```

and lmk the response

**Comment by kdurant** [comment]
I have installed the dressing.nvim and telescope.nvim plugins.
![2023-09-25_22-33](https://github.com/2KAbhishek/nerdy.nvim/assets/2704364/dc60402e-dce4-4d08-acfc-f8257c9fa108)

**Comment by 2KAbhishek** [comment]
I don't think they are properly configured, try checking this folder for the dressing and telescope lua configs

**Comment by 2KAbhishek** [comment]
I don't think they are properly configured, try checking this folder for the dressing and telescope lua configs

If things are configured correctly, you should see a telescope prompt instead, something like this:

![Screenshot_2023-09-25-22-25-37-352_com.termux-edit.jpg](https://github.com/2KAbhishek/nerdy.nvim/assets/25423853/51110150-6cf7-414f-b33a-c1d8c84e055c)

**Comment by 2KAbhishek** [comment]
closing this for now, you can reach out to me if you need help, ty
