### ISSUE TITLE
[Question]:  why dont just use 'telescope-symbols.nvim`

### ISSUE THREAD

**Issue by NormTurtle** [2KAbhishek/nerdy.nvim#3]
### Description of the bug

https://github.com/nvim-telescope/telescope-symbols.nvim

why dont just this ^ one? 
why nerdy.nvim is needed against it !  ? also nerdy uses dressingn too   , performace lose there

!!!!

### Steps To Reproduce

nope,

**Comment by 2KAbhishek** [comment]
Thanks for asking this, but the telescope symbols contain a lot more than just nerd font which sometimes gets in the way while picking glyphs, just a matter of convenience
