### ISSUE TITLE
[QUESTION]: Why skip certain icons?

### ISSUE THREAD

**Issue by Rolv-Apneseth** [2KAbhishek/nerdy.nvim#4]
Hi. First of all thanks for making this plugin, I do hate going to their site just to look for an icon!

Inspired by this plugin, I'm trying to make something similar for `rofi`, and I'm just wondering why you skip certain icons in `generator.py` (with the `MIN` and `MAX` vars)?

**Comment by 2KAbhishek** [comment]
That is the range within which we will have the glyphs, you can try expenting with it as well

Also, would be awesome to try out the rofi plugin, do share a link :)

**Comment by Rolv-Apneseth** [comment]
Sorry I don't think I understand fully. My question is, why not use the whole file?

And sure, I'll share a link here once I'm done

**Comment by 2KAbhishek** [comment]
The range between MIN and MAX actually picks out the nerd glyphs from the file, the other ones were inelligible (at the time of writing this script) UTF8 chars.

> you can try experimenting with it as well,

Let me know if the range needs updating

**Comment by Rolv-Apneseth** [comment]
Sorry for the late reply, not had any time to work on personal projects. From my testing, all the icons in that file seem ok and there doesn't seem to be any duplicate keys so maybe the range isn't necessary any more?

**Comment by Rolv-Apneseth** [comment]
Hey - just following up on this since you asked for me to share it here. This is the plugin I was working on: [rofi-nerdy](https://github.com/Rolv-Apneseth/rofi-nerdy) (if you see any issues let me know).

I'm using the full file of icons/glyphs in mine, seem OK as far as I can tell. The python script is in the [justfile](https://github.com/Rolv-Apneseth/rofi-nerdy/blob/c866c2759a2f66e0210105e2e6011827e4cf10d1/justfile#L35).

Thanks again for making this. I made sure to credit you in the README.
