### ISSUE TITLE
[ENH]: Display Unicode (and maybe other info) along side glyphs for more useability in font and glyph dev

### ISSUE THREAD

**Issue by MikeLemo1** [2KAbhishek/nerdy.nvim#7]
### Description

Title is pretty self explanatory, I'd be nice if you could add more search sources too

**Comment by 2KAbhishek** [comment]
Displaying the code idea is nice, I'll add it!
Let me know if you have points for other sources or any other info.

**Comment by MikeLemo1** [comment]
Hi It's actually something I noticed just now but why is the finder taking results from a copy pasted lua table file that "imitates" it's content instead of directly searching from the .ttf in "~/.local/share/fonts/HackNerdFont-Regular.ttf" noticed some icons are missing making it half useful for working with font.

Also an ability to view a "bigger" preview for the glyphs as well'd be nice.

**Comment by 2KAbhishek** [comment]
@MikeLemo1 the file path for fonts is not standard across systems and   managing that will be beyond the scope of this plugin, the glyphs displayed to you will always be based on your terminal's font settings

I'll suggest opening up another issue for the preview window size
